---
title: "About this award"
description: |
  Some additional details about the website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# <i class="fas fa-crosshairs"></i> Aim

Statistical software tools make a considerable difference to the daily life of an analyst. 

::: box

This Award aims to 

1. encourage statistical software development by providing formal recognition of these developments
2. showcase the pool of statistical software developers in our local communities and
3. raise awareness of the statistical tools developed by community members. 

:::

The use of open-source software (e.g. Python and R) are fast growing among users of programming languages, and are widely used for statistical computing and graphics. This Award focuses on open-source software because the methods are transparent to users, and many of the contributions are volunteered by the community with little remuneration or formal recognition. This is a factor which this Award aims to address. 


# <i class="fas fa-user"></i> Professor Dianne Cook

Professor Dianne Cook was born and raised in regional Australia. She completed her Bachelor of Science at the University of New England before heading to the USA to complete her PhD in Statistics at Rutgers University. Prof. Cook spent most of her academic career at the Department of Statistics at the Iowa State University before returning back to Australia in 2015 to join the Department of Econometrics and Business Statistics at Monash University. She is particularly well known for her research in visual inference and high-dimensional data visualisation and as an avid advocate of statistical software development. A number of students under her supervision have developed highly successful R packages, including Hadley Wickham who developed `ggplot2`, Yihui Xie who developed `knitr` and Earo Wang who developed `tsibble`.

# Criteria and structure

1. The Award is open to students, or students who graduated within one year of the application due date, of Victorian or Tasmanian tertiary institutes only. 
1. The Award is not open to any work that has won another software competition or award, although the applicant may submit separate work that is significantly different to any previously winning work. 
1. The applicant must have begun the development while enrolled as a student and must currently be a student or within a year since graduation at the time of application. 
1. The applicant does not need to be a SSA member to apply for this award. 
1. Both individuals and teams are eligible to participate in this competition. 
1. If the software development was a team effort, the major contribution should be that of the students. 
1. The winners may be asked to give a presentation about their tool in an event in 2022.
1. Judges will be drawn from expert statistical software developers who are not entrants in the current round. The judges will be preferably drawn from outside of Victoria and Tasmania. 
1. The submitted software must be open-source and actively maintained at the time of entry.
1. The applicant must submit:
1. Briefly discuss the importance of the software to statistical practice and discussing the advantages and disadvantages of the new contribution compared to existing implementations. Up to 400 words.
1. Attach any evidence of potential impact and usefulness to the community. 
1. Attach any accepted paper(s) related to the software. 
1. A written tutorial demonstrating the use of the software product with a limit of 4000 words that can be used for the website.
1. An installable software product (e.g. package or web app) with its source code for use by the judging panel. 1. It should be accompanied by enough information to allow the judges to effectively use and evaluate the software (including its design considerations). This information can be provided in a variety of ways, including but not limited to: a user manual, a manuscript, a website, or an online help resource for the package.
For team developers, a letter endorsing the major software development as student’s work.
1. All materials must be in English. 
1. All materials must be submitted by completing the application Google form before the application deadline
The decision of the judging panel is final.


Potential evidences of impact or usefulness:
Download metrics/citation of paper/Altmetric
Uses of the software for non-academic audiences, e.g. work used in health sector for policy decisions. 
