---
title: "Di Cook Award"
description: |
  Open-Source Statistical Software Award by Statistical Society Australia, Victorian Branch
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

Statistical software tools make a considerable difference to the daily life of an analyst. This Award aims to

1. encourage statistical software development by providing formal recognition of these developments, 
2. showcase the pool of statistical software developers in our local communities and 
3. raise awareness of the statistical tools developed by community members. 

The use of open-source software (e.g. Python and R) are fast growing among users of programming languages, and are widely used for statistical computing and graphics. This Award focuses on open-source software because the methods are transparent to users, and many of the contributions are volunteered by the community with little remuneration or formal recognition. This is a factor which this Award aims to address. As a technical note, proprietary software can present a barrier to evaluation, because judges may not have access and thus be unable to conduct a thorough assessment.

SSA Vic proposes to run a local statistical software award, named the Di Cook Award, eligible to both full-time and part-time students enrolled (or within one year of graduation) in an educational institution in Victoria or Tasmania. The software development needs to have been started while enrolled as a student. This makes a SSA student competition available in Victoria/Tasmania, on par with the NSW Branch and Canberra Branch, which have the J.B. Douglas Award and Dennis Trewin Prize, respectively, for their students. 
