---
title: "Rules of the award"
output: html_document
author: Statistical Society of Australia - Victorian Branch
---

# Rationale 

Statistical software tools make a considerable difference to the daily life of an analyst. This Award aims to 

1. encourage statistical software development by providing formal recognition of these developments,
2. showcase the pool of statistical software developers in our local communities and
3. raise awareness of the statistical tools available to the community. 

The Award focuses on open-source software as its use is fast growing with programming languages, such as Python and R, becoming widely used for statistical computing and graphics. Furthermore, many of the contributions to open-source software are volunteered by the community with little remuneration or formal recognition and this Award addresses this gap. In addition as a technical note, proprietary software provides a barrier for the judges who may not have access to the proprietary software thus making it hard to judge.
